#!/usr/bin/env python
# -*- coding:UTF-8 -*-
'''
Description: Metagene analysis for a single codon or a single amino acid starvation
Author: Li Fajin
Email: lifajin@westlake.edu.cn
Date: 2024-03-14 14:37:39
LastEditors: Li Fajin
LastEditTime: 2024-03-21 17:50:36
FilePath: \\ORFreferenced:\\Projects\\02. AA starvation\\ZZWorkSpace\\Part 4-Ribosome stalling at codon level or AA level\\CodonPausing\\CodonMetaAnalysis.py
'''

import re
import sys
import os
import pysam
import itertools
from collections import defaultdict
from itertools import groupby,chain
from Bio.Seq import translate
import numpy as np
import pandas as pd
from optparse import OptionParser
__version__=0.0


class bam_file_attr(object):
	"""Class for bam file attribute"""
	def __init__(self,bamName,bamLen,bamOffset,bamLegend):
		self.bamName=bamName
		self.bamLen=bamLen
		self.bamOffset=bamOffset
		self.bamLegend=bamLegend
def create_parser_for_codon_metageneplot():
	'''argument parser.'''
	usage="usage: python %prog [options]"
	parser=OptionParser(usage=usage,version=__version__)
	parser.add_option("-f","--bamListFile",action="store",type="string",default=None,dest="bamListFile",
			help="Bam file list, containing 4 columns.Namely bamFiles,readLength, offSet, bamLegend. '-f' and '-i, -r, -s, -t' parameters are mutually exclusive.default=%default.")
	parser.add_option("-i","--input", action="store",type="string",default=None,dest="bam_files",
			help="Input file(s) in bam format. All files should be split by comma e.g. 1.bam,2.bam,3.bam[required]. '-i' and '-f' are mutually exclusive. default=%default")
	parser.add_option("-c","--coordinateFile",action="store",type="string",dest="coorFile",
			help="The file should contain the coordinate of start and stop codon. Generated by OutputTranscriptInfo.py.[required]")
	parser.add_option("-o","--otput_prefix",action="store",type="string",dest="output_prefix",
			help="Prefix of output files.[required]")
	parser.add_option("-r","--specific_reads_length",action="store",type="string",dest="read_length",
			help="Specific the lenght to do analysis, comma split. e.g. '28,29,30'.If use all length set 'All'. Bam files diff length select split by '_' e.g. '28,29,30_ALL_27,28' [required]. '-r' and '-f' are mutually exclusive.")
	parser.add_option("-s","--offset",action="store",type="string",dest="read_offset",
			help="Specific the offset corresponding to read length, comma split. e.g. '12,13,13'. No offset set 0. Bam files diff offset select split by '_' e.g. '12,13,13_0_12,12' [required]. '-s' and '-f' are mutually exclusive.")
	parser.add_option("-t","--bam_file_legend",action="store",type="string",dest="bam_file_legend",
			help="The legend of each bam files, comma split. e.g. 'condition1,condition2,condition3' [required]. '-t' and '-f' are mutually exclusive.")
	parser.add_option("-M","--filter_mode",action="store",type="string",dest="mode",default='counts',
			help="Mode for filtering transcripts. Either 'counts' or 'RPKM'. default=%default.")
	parser.add_option('-S','--select_trans_list',action="store",type='string',dest='in_selectTrans',
			help="Selected transcript list used for metagene analysis.This files requires the first column must be the transcript ID  with a column name.")
	parser.add_option('--type1',action='store',type='string',dest='type1',default=None,
			help="The first motif you want to find. It must be a string with length equal to 3. e.g. AAA,CCC,GGG motifs. default=%default.")
	parser.add_option('--type2',action='store',type='string',dest='type2',default=None,
			help="The second motif you want to find. It must be a string with length equal to 1. e.g. A,T,C,G,R motifs. default=%default.")
	parser.add_option('--motifList1',action='store',type='string',dest='motifList1',default=None,
			help="The first motif list you want to find. Mutually exclusive with '--type1' '--type2'. default=%default")
	parser.add_option('--motifList2',action='store',type='string',dest='motifList2',default=None,
			help="The second motif list you want to find. Mutually exclusive with '--type1' '--type2'. default=%default")
	parser.add_option("-l","--minimum_cds_codon",action="store",type="int",default=150,dest="min_cds_codon",
			help="Minimum CDS codon (nt unit). CDS codons smaller than \"minimum_cds_codon\" will be skipped. default=%default")
	parser.add_option("-n","--minimum_cds_counts",action="store",type="int",default=64,dest="min_cds_counts",
			help="Minimum CDS counts. CDS counts smaller than \"min_cds_counts\" will be skipped. default=%default")
	parser.add_option("-F","--transcript_fasta",action="store",type="string",dest="transcript_fasta",
			help="Input the transcript fasta file used for motif detection and codon density calculation. cds sequences related with coorFile (longest.trans.info.txt) generated by GetProteinSequence.py")
	parser.add_option("--table",action="store",type="int",dest="geneticCode",default=1,
			help="Which genetic code to use. default is the standard code.table = 1, is the standard table, ref: https://www.ncbi.nlm.nih.gov/Taxonomy/Utils/wprintgc.cgi")
	parser.add_option('--id-type',action="store",type="string",dest="id_type",default="transcript_id",
			help="define the id type users input. the default is transcript id, if not, will be transformed into transcript id. default=%default")

	return parser

def parse_coorFile(coorFile):
		'''extract transcript information from coorFile generated by RiboCode'''
		startCodonCoorDict={}
		stopCodonCoorDict={}
		with open(coorFile,'r') as f:
			for coors in f:
				startCodonCoorDict[coors.strip().split('\t')[0]]=coors.strip().split('\t')[1]
				stopCodonCoorDict[coors.strip().split('\t')[0]]=coors.strip().split('\t')[2]
		return startCodonCoorDict,stopCodonCoorDict

def get_trans_length_dict(transcriptFile):
	'''
	This function is used to get a dict of transcript length
	'''
	trans_length_dict={}
	transFile=open(transcriptFile,'r')
	faiter=(x[1] for x in groupby(transFile,lambda line: line.strip()[0]==">")) ## groupby returns a tuple (key, group)
	for header in faiter:
		trans_id=header.__next__().strip(">").split(" ")[0]
		seq=''.join(s.strip() for s in faiter.__next__())
		length=int(len(seq.strip()))
		trans_length_dict[trans_id]=length
	return trans_length_dict

def reload_transcripts_information(longestTransFile):
	selectTrans=set()
	transLengthDict={}
	cdsLengthDict={}
	startCodonCoorDict={}
	stopCodonCoorDict={}
	transID2geneID={}
	transID2geneName={}
	transID2ChromDict={}
	with open(longestTransFile,'r') as f:
		for line in f:
			if line.strip()=='':
				continue
			if line.strip().split("\t")[0] == 'chrom':
				continue
			chrom=line.strip().split("\t")[0]
			transID=line.strip().split("\t")[1]
			geneID=line.strip().split("\t")[3]
			geneName=line.strip().split("\t")[4]
			startCodon=int(line.strip().split("\t")[8])
			stopCodon=int(line.strip().split("\t")[9])
			cds_length=int(line.strip().split("\t")[10])
			transLength=int(line.strip().split("\t")[13])
			selectTrans.add(transID)
			transLengthDict[transID]=transLength
			startCodonCoorDict[transID]=startCodon
			stopCodonCoorDict[transID]=stopCodon
			transID2geneID[transID]=geneID
			transID2geneName[transID]=geneName
			cdsLengthDict[transID]=cds_length
			transID2ChromDict[transID]=chrom
			# print(transID,geneID,geneName,startCodon,stopCodon,transLength)
	print(str(len(selectTrans))+'  transcripts will be used in the follow analysis.\n', file=sys.stderr)
	return selectTrans,transLengthDict,startCodonCoorDict,stopCodonCoorDict,transID2geneID,transID2geneName,cdsLengthDict,transID2ChromDict

def lengths_offsets_split(value):
		''' Split the given comma separated values to multiple integer values'''
		values=[]
		for item in value.split(','):
				item=int(item)
				values.append(item)
		return values

def get_trans_frame_counts(ribo_fileobj, transcript_name, read_lengths, read_offsets, transLength, startCoor, stopCoor):
	"""For each mapped read of the given transcript in the BAM file,get the P-site and codon unit reads density
	ribo_fileobj -- file object - BAM file opened using pysam AlignmentFile
	transcript_name -- Name of transcript to get counts for
	read_length -- If provided, get counts only for reads of this length.
	read_offsets -- the offset length corresponding to 5' mapped position.
	transLength -- the length of the transcript.
	startCoor -- the coordinate of the first base of start codon 0-based.
	stopCoor -- the coordinate of the first base of stop codon 0-based.
	"""
	read_counts = np.zeros(transLength,dtype="int64")
	total_reads = 0
	if read_lengths == "ALL" : ## RNA
		for record in ribo_fileobj.fetch(transcript_name):
			if record.flag == 16 or record.flag == 272:
				continue
			total_reads += 1
			position = record.pos
			read_counts[position]+=1
	else:
		read_lengths=lengths_offsets_split(read_lengths)
		read_offsets=lengths_offsets_split(read_offsets)
		for record in ribo_fileobj.fetch(transcript_name):
			if record.flag == 16 or record.flag == 272:
				continue
			for R_length, R_offset in zip(read_lengths,read_offsets):
				if  record.query_length == R_length :
					# if an offset is specified, increment position by that offset.
					position = record.pos + R_offset ## transform into the position of P-site
				else:
					# ignore other reads/lengths
					continue
				total_reads += 1
				try:
					read_counts[position]+=1
				except KeyError:
					print("Dont has this position after offset : transcript_name -> position"+" "+transcript_name+" -> "+position)
	#get trans counts for each 3 frames
	read_counts_frame0=read_counts[(startCoor+0):(stopCoor-2):3]
	read_counts_frame1=read_counts[(startCoor+1):(stopCoor-1):3]
	read_counts_frame2=read_counts[(startCoor+2):(stopCoor-0):3]
	read_counts_frameSum=read_counts_frame0+read_counts_frame1+read_counts_frame2
	cds_reads=sum(read_counts_frameSum)
	return read_counts,read_counts_frameSum,total_reads,cds_reads



def parse_bamListFile(bamListFile):
	bamFileList=[]
	readLengthsList=[]
	OffsetsList=[]
	bamLegendsList=[]
	flag=1
	with open(bamListFile,'r') as f:
		for line in f:
			if flag == 1:
				flag+=1
				continue
			bamFile=line.strip().split("\t")[0]
			readLengths=line.strip().split("\t")[1]
			Offsets=line.strip().split("\t")[2]
			bamLegends=line.strip().split("\t")[3]
			bamFileList.append(bamFile)
			readLengthsList.append(readLengths)
			OffsetsList.append(Offsets)
			bamLegendsList.append(bamLegends)
	return bamFileList,readLengthsList,OffsetsList,bamLegendsList

def fastaIter(transcriptFile):
	'''
	This function is used to get a dict of transcript sequence
	'''
	fastaDict={}
	f=open(transcriptFile,'r')
	faiter=(x[1] for x in groupby(f,lambda line: line.strip()[0]==">")) ## groupby returns a tuple (key, group)
	for header in faiter:
		geneName=header.__next__().strip(">").split(" ")[0]
		seq=''.join(s.strip() for s in faiter.__next__())
		flag=0
		for nt in ['I','K','M','R','S','W','Y','B','D','H','V','N','X']:
			if nt in seq:
				flag+=1
				flag_nt=nt
		if flag != 0:
			print(geneName+" filtered"+"--"+"There is a ambiguous nucleotide",flag_nt,"in your sequence")
			continue
		fastaDict[geneName]=seq
	return fastaDict

def reverse_complement(seq):
	seq_rc=''.join(["AUCGN"["UAGCN".index(n)] for n in seq[::-1]])
	return seq_rc

def translation(seq,table=1,cds=True):
	"""
	translate the DNA to protein sequence using the translation table
	table = 1, is the standard table, ref: https://www.ncbi.nlm.nih.gov/Taxonomy/Utils/wprintgc.cgi
	Code from RiboCode.[Xiao,et al. NAR. 2018]
	"""
	if len(seq) % 3 != 0:
		sys.stderr.write("Warning: sequence is not divisible by 3\n")
		seq = seq[:-(len(seq) % 3)]
	return translate(seq,table=table,cds=cds)

def flatten(xs):
	for x in xs:
		if isinstance(x,tuple):
			for xx in flatten(x):
				yield xx
		else:
			yield x
   
def IDtransForm(in_selectTrans,coorFile,id_type):
	selectTrans,transLengthDict,startCodonCoorDict,stopCodonCoorDict,transID2geneID,transID2geneName,cdsLengthDict,transID2ChromDict=reload_transcripts_information(coorFile)
	geneID2transID={v:k for k,v in transID2geneID.items()}
	geneName2transID={v:k for k,v in transID2geneName.items()}
	if in_selectTrans:
		select_trans=pd.read_csv(in_selectTrans,sep="\t")
		select_trans=set(select_trans.iloc[:,0].values)
		if id_type == 'transcript_id':
			select_trans=select_trans.intersection(selectTrans)
			print("There are " + str(len(select_trans)) + " transcripts from "+in_selectTrans+" used for following analysis.",file=sys.stderr)
		elif id_type == 'gene_id':
			tmp=[geneID2transID[gene_id] for gene_id in select_trans if gene_id in geneID2transID]
			select_trans=set(tmp)
			select_trans=select_trans.intersection(selectTrans)
			print("There are " + str(len(select_trans))+" gene id could be transformed into transcript id and used for following analysis.",file=sys.stderr)
		elif id_type == 'gene_name' or id_type=='gene_symbol':
			tmp=[geneName2transID[gene_name] for gene_name in select_trans if gene_name in geneName2transID]
			select_trans=set(tmp)
			select_trans=select_trans.intersection(selectTrans)
			print("There are " + str(len(select_trans))+" gene symbol could be transformed into transcript id and used for following analysis.",file=sys.stderr)
		else:
			raise IOError("Please input a approproate id_type parameters.[transcript_id/gene_id/gene_name/]")
	else:
		select_trans=selectTrans

	return select_trans,transLengthDict,startCodonCoorDict,stopCodonCoorDict

def nonzeroMean(data):
	nonzeroidx=np.nonzero(data)
	nonzeroval=data[nonzeroidx]
	meanval=np.mean(nonzeroval)
	if np.isnan(meanval):
		return 0
	else:
		return meanval



def find_motif(in_bamFile,in_selectTrans,in_transLengthDict,in_startCodonCoorDict,in_stopCodonCoorDict,in_readLengths,in_readOffset,inCDS_countsFilterParma,inCDS_lengthFilterParma,transcriptFasta,type1=None,type2=None,motifList1=None,motifList2=None,mode='counts',table=1):
	'''
	find a specific triplete AA motif (PPP) and its ribosome density or find a set of motifs provided by the motifList and get their ribosome densities.
	'''
	transcript_sequence=fastaIter(transcriptFasta)
	filter_1=0
	filter_2=0
	filter_3=0
	filter_4=0
	filter_5=0
	all_counts=0
	passTransSet=set()
	motifDensity_1=defaultdict(list)
	tmpMotifDensity_1=defaultdict(list)
	motifDensity_2=defaultdict(list)
	tmpMotifDensity_2=defaultdict(list)
	RecordList1=[]
	RecordList2=[]

	if type1:
		type1_AA=list(type1.strip())
		print(len(type1_AA))
		if len(type1_AA) != 3:
			raise IOError("The type1 must be a string with lenght equaling to 3. e,g. 'AAA' or 'GGG' motifs")
		else:
			pass
	if type2:
		type2_AA=list(type2.strip())
		if len(type2_AA) != 1:
			raise IOError("The type2 must be a string with lenght equaling to 1. e,g. 'P' or 'K' or 'R' motifs")
		else:
			pass
	if motifList1:
		motifList1_motif=pd.read_csv(motifList1,sep="\t")
		motifList1_motif=motifList1_motif.iloc[:,0].values
	if motifList2:
		motifList2_motif=pd.read_csv(motifList2,sep="\t")
		motifList2_motif=motifList2_motif.iloc[:,0].values

	if (type1 or type2) and (motifList1 or motifList2):
		raise IOError("The 'type' parameters and 'motifList' parameters are mutually exclusive. Please input one of them.")

	if (not type1 and not type2) and  (not motifList1 and not motifList2):
		raise IOError("There is at least one parameters among the 'typ1' 'type2' 'motifList1' and 'motifList2'.")

	## read sam files
	pysamFile=pysam.AlignmentFile(in_bamFile,"rb")
	pysamFile_trans=pysamFile.references
	in_selectTrans=set(pysamFile_trans).intersection(in_selectTrans)
	in_selectTrans=in_selectTrans.intersection(transcript_sequence.keys()).intersection(in_startCodonCoorDict.keys())
	for trans in in_startCodonCoorDict.keys():
		leftCoor =int(in_startCodonCoorDict[trans])-1
		rightCoor=int(in_stopCodonCoorDict[trans])-3
		(trans_counts,read_counts_frameSum,total_reads,cds_reads)=get_trans_frame_counts(pysamFile, trans, in_readLengths, in_readOffset, in_transLengthDict[trans], leftCoor, rightCoor)
		all_counts+=total_reads
	for trans in in_selectTrans:
		leftCoor =int(in_startCodonCoorDict[trans])-1 #the first base of start codon 0-base
		rightCoor=int(in_stopCodonCoorDict[trans])-3 #the first base of stop codon 0-base
		CDS_seq=transcript_sequence[trans]
		if len(CDS_seq) % 3 !=0:
			filter_1+=1
			continue
		if len(CDS_seq) < inCDS_lengthFilterParma:
			filter_2+=1
		AA_seq=translation(CDS_seq,table=table,cds=False)
		codon_seq=[CDS_seq[i:(i+3)] for i in range(0,len(CDS_seq),3)]

		## read counts
		(read_counts,read_counts_frameSum,trans_reads,cds_reads)=get_trans_frame_counts(pysamFile, trans, in_readLengths, in_readOffset, in_transLengthDict[trans], leftCoor, rightCoor)
		read_counts=10**6*(read_counts/all_counts)
		cds_reads_normed = 10**9*(cds_reads/(all_counts*len(read_counts_frameSum)*3))
		if mode == "RPKM":
			if cds_reads_normed < inCDS_countsFilterParma:
				filter_3+=1
				continue
		if mode == 'counts':
			if cds_reads < inCDS_countsFilterParma:
				filter_3+=1
				continue
		## get read density in nt unit
		read_counts_frame=np.array(read_counts[leftCoor:rightCoor+3])
		sumValue=sum(read_counts_frame[20:(len(AA_seq)-20)]) ## count from the 20th, and stop at len(AA_seq)-20
		# meanValue=np.mean(read_counts_frame[20:(len(AA_seq)-20)])
		meanValue=nonzeroMean(read_counts_frame)
		if meanValue==0:
			filter_4+=1
			continue
		## normalize the read_counts_frame by total density/mean density along the whole AA sequence
		densityPerTrans=read_counts_frame/meanValue
		# densityPerTrans=densityPerTrans/np.mean(densityPerTrans)
  
		tmpMotif2=np.zeros(201,dtype="float64")
		tmpMotif1=np.zeros(201,dtype="float64")
		passTransSet.add(trans)
		if (type1 and (not type2) and (not motifList1) and (not motifList2)):
			motif=type1
			for  i in np.arange(35,(len(codon_seq)-35)): # there is no AA on position len(AA_seq)+1,scan from the 21 codon and stop at 21 codon away from stop codon
				if codon_seq[i]== motif:
					if len(densityPerTrans[(i*3-100):(i*3+100+1)])<201:
						filter_5+=1
						continue
					tmpMotif1+=densityPerTrans[(i*3-100):(i*3+100+1)]
					tmpMotifDensity_1[motif].append(tmpMotif1)
					record=trans+"\t"+motif+codon_seq[i+2]+"\t"+str(i)+"\t"+str(sum(densityPerTrans[i*3:(i*3+3)])) ## E-site
					#print(record,file=sys.stderr)
					RecordList1.append(record)
		elif (type2 and (not type1) and (not motifList1) and (not motifList2)):
			motif=type2
			for  i in np.arange(35,(len(AA_seq)-35)): # there is no AA on position len(AA_seq)+1,scan from the 21 codon and stop at 21 codon away from stop codon
				if AA_seq[i]== motif:
					if len(densityPerTrans[(i*3-100):(i*3+100+1)])<201:
						filter_5+=1
						continue
					tmpMotif2+=densityPerTrans[(i*3-100):(i*3+100+1)]
					tmpMotifDensity_2[motif].append(tmpMotif2)
					record=trans+"\t"+motif+"\t"+str(i)+"\t"+str(sum(densityPerTrans[(i*3+3):(i*3+6)])) ## P-site
					#print(record,file=sys.stderr)
					#print(trans,motif,i,file=sys.stderr)
					RecordList2.append(record)
		elif (type1 and type2 and (not motifList1) and (not motifList2)):
			motif1=type1
			motif2=type2
			for  i in np.arange(35,(len(AA_seq)-35)): # there is no AA on position len(AA_seq)+1,scan from the 21 codon and stop at 21 codon away from stop codon
				if codon_seq[i]== motif1:
					if len(densityPerTrans[(i*3-100):(i*3+100+1)])<201:
						filter_5+=1
						continue
					tmpMotif1+=densityPerTrans[(i*3-100):(i*3+100+1)]
					tmpMotifDensity_1[motif1].append(tmpMotif1)
					record=trans+"\t"+motif1+codon_seq[i+2]+"\t"+str(i)+"\t"+str(sum(densityPerTrans[i*3:(i*3+3)]))
					#print(record,file=sys.stderr)
					RecordList1.append(record)
				if AA_seq[i]== motif2:
					if len(densityPerTrans[(i*3-100):(i*3+100+1)])<201:
						filter_5+=1
						continue
					tmpMotif2+=densityPerTrans[(i*3-100):(i*3+100+1)]
					tmpMotifDensity_2[motif2].append(tmpMotif2)
					record=trans+"\t"+motif2+"\t"+str(i)+"\t"+str(sum(densityPerTrans[(i*3+3):(i*3+6)]))
					#print(record,file=sys.stderr)
					RecordList2.append(record)
		elif ((not type1) and (not type2) and motifList1 and (not motifList2)):
			for tmpMotif in motifList1_motif:
				for  i in np.arange(35,(len(codon_seq)-35)): # there is no AA on position len(AA_seq)+1,scan from the 21 codon and stop at 21 codon away from stop codon
					motif=codon_seq[i]
					if motif == tmpMotif:
						if len(densityPerTrans[(i*3-100):(i*3+100+1)])<201:
							filter_5+=1
							continue
						tmpMotif1+=densityPerTrans[(i*3-100):(i*3+100+1)]
						tmpMotifDensity_1[motif].append(tmpMotif1)
						record=trans+"\t"+motif+"\t"+str(i)+"\t"+str(sum(densityPerTrans[i*3:(i*3+3)]))
						#print(record,file=sys.stderr)
						RecordList1.append(record)
		elif ((not type1) and (not type2) and (not motifList1) and motifList2):
			for tmpMotif in motifList2_motif:
				for  i in np.arange(35,(len(AA_seq)-35)): # there is no AA on position len(AA_seq)+1,scan from the 21 codon and stop at 21 codon away from stop codon
					motif=AA_seq[i]
					if motif == tmpMotif:
						if len(densityPerTrans[(i*3-100):(i*3+100+1)])<201:
							filter_5+=1
							continue
						tmpMotif2+=densityPerTrans[(i*3-100):(i*3+100+1)]
						tmpMotifDensity_2[motif].append(tmpMotif2)
						record=trans+"\t"+motif+"\t"+str(i)+"\t"+str(sum(densityPerTrans[(i*3+3):(i*3+6)]))
						#print(record,file=sys.stderr)
						RecordList2.append(record)
		elif ((not type1) and (not type2) and motifList1 and motifList2):
			for tmpMotif in motifList1_motif:
				for  i in np.arange(35,(len(codon_seq)-35)): # there is no AA on position len(AA_seq)+1,scan from the 21 codon and stop at 21 codon away from stop codon
					motif1=codon_seq[i]
					if motif1 == tmpMotif:
						# print(len(CDS_seq),len(codon_seq),len(densityPerTrans),len(densityPerTrans[(i*3-100):(i*3+100+1)]),file=sys.stderr)
						if len(densityPerTrans[(i*3-100):(i*3+100+1)])<201:
							filter_5+=1
							continue
						tmpMotif1+=densityPerTrans[(i*3-100):(i*3+100+1)]
						tmpMotifDensity_1[motif1].append(tmpMotif1)
						record=trans+"\t"+motif1+"\t"+str(i)+"\t"+str(sum(densityPerTrans[i*3:(i*3+3)]))
						#print(record,file=sys.stderr)
						RecordList1.append(record)
			for tmpMotif in motifList2_motif:
				for  i in np.arange(35,(len(AA_seq)-35)):
					motif2=AA_seq[i]
					if motif2 == tmpMotif:
						if len(densityPerTrans[(i*3-100):(i*3+100+1)])<201:
							filter_5+=1
							continue
						tmpMotif2+=densityPerTrans[(i*3-100):(i*3+100+1)]
						tmpMotifDensity_2[motif2].append(tmpMotif2)
						record=trans+"\t"+motif2+"\t"+str(i)+"\t"+str(sum(densityPerTrans[(i*3+3):(i*3+6)]))
						#print(record,file=sys.stderr)
						RecordList2.append(record)
		else:
			raise IOError("Please check your input!")

	pysamFile.close()
	print("The number of genes whose length of CDS could not divided by three: " + str(filter_1),file=sys.stderr)
	print("The number of genes whose length of CDS is less than the criteria: " + str(filter_2),file=sys.stderr)
	print("The number of genes whose read counts on CDS are less than the criteria: " + str(filter_3),file=sys.stderr)
	print("The number of genes whose total read counts after normalization are equal to zero: "+str(filter_4),file=sys.stderr)
	print("The number of positions whose density length than 201: "+str(filter_5),file=sys.stderr)
	print("The final number of genes used for following analysis is: " + str(len(passTransSet)),file=sys.stderr)

	if tmpMotifDensity_1 and (not tmpMotifDensity_2):
		for k,v in tmpMotifDensity_1.items():
			tmpMotif1=k
			tmpDensity1=np.array(v)
			print("There are "+str(tmpDensity1.shape[0])+" positions used for plot "+ str(tmpMotif1),file=sys.stderr)
			for i in np.arange(201):
				motifDensity_1[tmpMotif1].append(np.mean(tmpDensity1[:,i]))
			motifDensity_1[tmpMotif1]=np.array(motifDensity_1[tmpMotif1])/np.mean(np.array(motifDensity_1[tmpMotif1]))
		print("This will return motifDensity_1",file=sys.stderr)
		#print(len(RecordList1),file=sys.stderr)
		return motifDensity_1,RecordList1
	if (not tmpMotifDensity_1) and tmpMotifDensity_2:
		for k,v in tmpMotifDensity_2.items():
			tmpMotif2=k
			tmpDensity2=np.array(v)
			print("There are "+ str(tmpDensity2.shape[0])+" positions used for plot "+ str(tmpMotif2),file=sys.stderr)
			for i in np.arange(201):
				motifDensity_2[tmpMotif2].append(np.mean(tmpDensity2[:,i]))
			motifDensity_2[tmpMotif2]=np.array(motifDensity_2[tmpMotif2])/np.mean(np.array(motifDensity_2[tmpMotif2]))
		print(len(RecordList2),file=sys.stderr)
		#print("This will return motifDensity_2",file=sys.stderr)
		return motifDensity_2,RecordList2
	if tmpMotifDensity_1 and tmpMotifDensity_2:
		for k,v in tmpMotifDensity_1.items():
			tmpMotif1=k
			tmpDensity1=np.array(v)
			print("There are "+str(tmpDensity1.shape[0])+" positions used for plot "+ str(tmpMotif1) ,file=sys.stderr)
			for i in np.arange(201):
				motifDensity_1[tmpMotif1].append(np.mean(tmpDensity1[:,i]))
			motifDensity_1[tmpMotif1]=np.array(motifDensity_1[tmpMotif1])/np.mean(np.array(motifDensity_1[tmpMotif1]))
		for k,v in tmpMotifDensity_2.items():
			tmpMotif2=k
			tmpDensity2=np.array(v)
			print("There are "+ str(tmpDensity2.shape[0])+" positions used for plot " + str(tmpMotif2),file=sys.stderr)
			for i in np.arange(201):
				motifDensity_2[tmpMotif2].append(np.mean(tmpDensity2[:,i]))
			motifDensity_2[tmpMotif2]=np.array(motifDensity_2[tmpMotif2])/np.mean(np.array(motifDensity_2[tmpMotif2]))
		if len(tmpMotifDensity_1.keys())>1 or len(tmpMotifDensity_2.keys())>1:
			motifDensity_1['sum_list1']=np.array(list(map(sum,zip(*motifDensity_1.values()))))
			motifDensity_2['sum_list2']=np.array(list(map(sum,zip(*motifDensity_2.values()))))
		print("This will return motifDensity_1 and motifDensity_2",file=sys.stderr)
		#print(len(RecordList1),len(RecordList2),file=sys.stderr)
		return motifDensity_1,motifDensity_2,RecordList1,RecordList2


def write_mofitDensity_dataframe_two_types(inBamAttr,outFile):
		data=[]
		data_columns=[]
		for bms in inBamAttr:
			tmpmotif1=list(chain(*[[i]*len(bms.motifDensity_1[i]) for i in bms.motifDensity_1.keys()]))
			tmpmotif2=list(chain(*[[i]*len(bms.motifDensity_2[i]) for i in bms.motifDensity_2.keys()]))
			tmpdensity1=list(chain(*[bms.motifDensity_1[i] for i in bms.motifDensity_1.keys()]))
			tmpdensity2=list(chain(*[bms.motifDensity_2[i] for i in bms.motifDensity_2.keys()]))
			density1=pd.DataFrame(tmpdensity1)
			density2=pd.DataFrame(tmpdensity2)
			sample=bms.bamLegend
			motif=pd.DataFrame(tmpmotif1+tmpmotif2)
			density=pd.concat((density1,density2),axis=0)
			data_columns.append(sample)
			data.append(density)
		temp=data[0]
		if len(data) < 1:
			raise EOFError("Empty file, there is nothing in the file.")
		if len(data) == 1:
			data_columns=["motif"]+data_columns
			temp=pd.DataFrame(pd.merge(motif,temp,how='left',left_index=True,right_index=True))
			temp.columns=data_columns
			temp.to_csv(outFile,sep="\t",index=0)
		if len(data) > 1:
			for i in np.arange(1,len(data)):
				temp=np.hstack((temp,data[i]))
			data_columns=["motif"]+data_columns
			temp=pd.DataFrame(temp)
			temp=pd.DataFrame(pd.merge(motif,temp,how='left',left_index=True,right_index=True))
			temp.columns=data_columns
			temp.to_csv(outFile,sep="\t",index=0)
def write_mofitDensity_dataframe_one_type(inBamAttr,outFile):
		data=[]
		data_columns=[]
		for bms in inBamAttr:
			tmpmotif=list(chain(*[[i]*len(bms.motifDensity[i]) for i in bms.motifDensity.keys()]))
			tmpdensity=list(chain(*[bms.motifDensity[i] for i in bms.motifDensity.keys()]))
			density=pd.DataFrame(tmpdensity)
			sample=bms.bamLegend
			motif=pd.DataFrame(tmpmotif)
			data_columns.append(sample)
			data.append(density)
		temp=data[0]
		if len(data) < 1:
			raise EOFError("Empty file, there is nothing in the file.")
		if len(data) == 1:
			data_columns=["motif"]+data_columns
			temp=pd.DataFrame(pd.merge(motif,temp,how='left',left_index=True,right_index=True))
			temp.columns=data_columns
			temp.to_csv(outFile,sep="\t",index=0)
		if len(data) > 1:
			for i in np.arange(1,len(data)):
				temp=np.hstack((temp,data[i]))
			data_columns=["motif"]+data_columns
			temp=pd.DataFrame(temp)
			temp=pd.DataFrame(pd.merge(motif,temp,how='left',left_index=True,right_index=True))
			temp.columns=data_columns
			temp.to_csv(outFile,sep="\t",index=0)


def parse_args_for_codon_metageneplot():
	parsed=create_parser_for_codon_metageneplot()
	(options,args)=parsed.parse_args()
	(type1,type2,motifList1,motifList2,min_cds_counts,min_cds_codon,transcript_fasta,mode,output_prefix,table)=(options.type1,options.type2,options.motifList1,options.motifList2,
	options.min_cds_counts,options.min_cds_codon,options.transcript_fasta,options.mode,options.output_prefix,options.geneticCode)
	if options.bamListFile and (options.bam_files or options.read_length or options.read_offset or options.bam_file_legend):
		raise IOError("'-f' parameter and '-i -r -s -t' are mutually exclusive.")
	if options.bamListFile:
		bamFiles,readLengths,Offsets,bamLegends=parse_bamListFile(options.bamListFile)
	elif options.bam_files:
		bamFiles,readLengths,Offsets,bamLegends=options.bam_files.split(","),options.read_length.split("_"),options.read_offset.split("_"),options.bam_file_legend.split(",")
	else:
		raise IOError("Please check you input files!")
	print("your input : "+ str(len(bamFiles))+" bam files",file=sys.stderr)
	bam_attr=[]
	for ii,jj,mm,nn in zip(bamFiles,readLengths,Offsets,bamLegends):
		bam=bam_file_attr(ii,jj,mm,nn)
		bam_attr.append(bam)
	select_trans,transLengthDict,startCodonCoorDict,stopCodonCoorDict=IDtransForm(options.in_selectTrans,options.coorFile,options.id_type)

	if (type1 and (not type2) and (not motifList1) and (not motifList2)):
		for bamfs in bam_attr:
			print("Start analyze the sample: "+str(bamfs.bamName),file=sys.stderr)
			(bamfs.motifDensity,bamfs.RecordList1)=find_motif(bamfs.bamName,select_trans,transLengthDict,startCodonCoorDict,stopCodonCoorDict,bamfs.bamLen,bamfs.bamOffset,min_cds_counts,min_cds_codon,
			transcript_fasta,type1=type1.strip(),mode=mode,table=table)
			print("Finish the step of calculate the motif density of genes",file=sys.stderr)
		## output density
		# write_motif_list(bam_attr,output_prefix,'di-AA')
		write_mofitDensity_dataframe_one_type(bam_attr,output_prefix+"_motifDensity_dataframe.txt")
		print("Finish the step of write motif density file!",file=sys.stderr)

	if (type2 and (not type1) and (not motifList1) and (not motifList2)):
		for bamfs in bam_attr:
			print("Start analyze the sample: "+str(bamfs.bamName),file=sys.stderr)
			bamfs.motifDensity,bamfs.RecordList2=find_motif(bamfs.bamName,select_trans,transLengthDict,startCodonCoorDict,stopCodonCoorDict,bamfs.bamLen,bamfs.bamOffset,min_cds_counts,min_cds_codon,
			transcript_fasta,type2=type2.strip(),mode=mode,table=table)
			print("Finish the step of calculate the motif density of genes",file=sys.stderr)
		## output density
		# write_motif_list(bam_attr,output_prefix,'tri-AA')
		write_mofitDensity_dataframe_one_type(bam_attr,output_prefix+"_motifDensity_dataframe.txt")
		print("Finish the step of write motif density file!",file=sys.stderr)

	if (type1 and type2 and (not motifList1) and (not motifList2)):
		for bamfs in bam_attr:
			print("Start analyze the sample: "+str(bamfs.bamName),file=sys.stderr)
			(bamfs.motifDensity_1,bamfs.motifDensity_2,bamfs.RecordList1,bamfs.RecordList2)=find_motif(bamfs.bamName,select_trans,transLengthDict,startCodonCoorDict,stopCodonCoorDict,bamfs.bamLen,bamfs.bamOffset,min_cds_counts,min_cds_codon,
			transcript_fasta,type1=type1,type2=type2,mode=mode,table=table)
			print("Finish the step of calculate the motif density of genes",file=sys.stderr)
		## output density
		# write_motif_list(bam_attr,output_prefix,'both')
		write_mofitDensity_dataframe_two_types(bam_attr,output_prefix+"_motifDensity_dataframe.txt")
		print("Finish the step of write motif density file!",file=sys.stderr)

	if ((not type1) and (not type2) and motifList1 and (not motifList2)):
		for bamfs in bam_attr:
			print("Start analyze the sample: "+str(bamfs.bamName),file=sys.stderr)
			bamfs.motifDensity,bamfs.RecordList1=find_motif(bamfs.bamName,select_trans,transLengthDict,startCodonCoorDict,stopCodonCoorDict,bamfs.bamLen,bamfs.bamOffset,min_cds_counts,min_cds_codon,
			transcript_fasta,motifList1=motifList1,mode=mode,table=table)
			print("Finish the step of calculate the motif density of genes",file=sys.stderr)
		## output density
		# write_motif_list(bam_attr,output_prefix,'di-AA')
		write_mofitDensity_dataframe_one_type(bam_attr,output_prefix+"_motifDensity_dataframe.txt")
		print("Finish the step of write motif density file!",file=sys.stderr)

	if ((not type1) and (not type2) and (not motifList1) and motifList2):
		for bamfs in bam_attr:
			print("Start analyze the sample: "+str(bamfs.bamName),file=sys.stderr)
			bamfs.motifDensity,bamfs.RecordList2=find_motif(bamfs.bamName,select_trans,transLengthDict,startCodonCoorDict,stopCodonCoorDict,bamfs.bamLen,bamfs.bamOffset,min_cds_counts,min_cds_codon,
			transcript_fasta,motifList2=motifList2,mode=mode,table=table)
			print("Finish the step of calculate the motif density of genes",file=sys.stderr)
		## output density
		# write_motif_list(bam_attr,output_prefix,'tri-AA')
		write_mofitDensity_dataframe_one_type(bam_attr,output_prefix+"_motifDensity_dataframe.txt")
		print("Finish the step of write motif density file!",file=sys.stderr)

	if ((not type1) and (not type2) and motifList1 and motifList2):
		for bamfs in bam_attr:
			print("Start analyze the sample: "+str(bamfs.bamName),file=sys.stderr)
			(bamfs.motifDensity_1,bamfs.motifDensity_2,bamfs.RecordList1,bamfs.RecordList2)=find_motif(bamfs.bamName,select_trans,transLengthDict,startCodonCoorDict,stopCodonCoorDict,bamfs.bamLen,bamfs.bamOffset,min_cds_counts,min_cds_codon,
			transcript_fasta,motifList1=motifList1,motifList2=motifList2,mode=mode,table=table)
			print("Finish the step of calculate the motif density of genes",file=sys.stderr)
		## output density
		# write_motif_list(bam_attr,output_prefix,'both')
		write_mofitDensity_dataframe_two_types(bam_attr,output_prefix+"_motifDensity_dataframe.txt")
		print("Finish the step of write motif density file!",file=sys.stderr)



def main():
	"""main program"""
	parse_args_for_codon_metageneplot()

if __name__ == "__main__":
		main()